name: Concurrency 1
run-name: Concurrency 1 (${{ inputs.environment }})
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: 'environment'
        required: true
    
# used to avoid having multiple workflows running at the same time, it will run only the last one
concurrency: 
  # group: concurrency-1
  # by making the group dinamic, it will run only the last workflow with the same group name
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  cancel-in-progress: true
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
          - run: sleep 30