name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
      runs-on: ubuntu-latest
      container:
        image: node:22-alpine3.19
        # credentials:
        #   username:
        #   password:
        env:
          API_URL: some-url.com
        ports:
          - 80
        # volumes:
        #   - vol_name:/path/in/container
        #   - /path/to/container
        #   - /path/in/host:/path/in/container
        # options: --cpus 1
      steps:
        - name: Log Node & OS Versions
          run: |
            node -v
            cat /etc/os-release
        - name: Log Environment Variables
          run: echo $API_URL
        - name: Create a file
          run: echo 'Some text' > file.txt
        - name: Container in a Step
          uses: docker://node:20-alpine3.19
          with:
            entrypoint: /usr/local/bin/node
            args: -p 3+3
        - name: Log node version
          uses: docker://node:18-alpine3.19
          with:
            args: -v
        - name: Display file contents
          uses: docker://node:18-alpine3.19
          with:
            entrypoint: cat
            args: file.txt
        - uses: actions/checkout@v4
        - name: Run a bash script
          uses: docker://node:18-alpine3.19
          with:
            # Run
            # Windows: git add --chmod=+x .\script.sh
            # Linux/mac: chmod +x script.sh
            entrypoint: ./script.sh
            args: "Some Script"
        # WEX doesn't support Slack access
        # - name: Send a slack message
        #   uses: docker://technosophos/slack-notify
        #   env:
        #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #     SLACK_USERNAME: GitHub Actions
        #     SLACK_TITLE: From github actions
        #     SLACK_MESSAGE: "Actor: ${{ github.actor }}, Event: ${{ github.event_name }}"
        #     SLACK_COLOR: "#723fc4"
        #     SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png