name: Expressions and Contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions and Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"
jobs:
    using_expressions-and-contexts:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Expressions
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'Thisi is a string' }}
                echo ${{ null }}
                echo ${{ false }}
                echo ${{ 1 > 2 }}
                echo ${{ 'string' == 'String' }}
                echo ${{ true && false }}
                echo ${{ true || (false && true) }}
            - name: Dump Contexts
              run: |
                echo '${{ toJson(github) }}'
                echo '${{ toJson(job) }}'
                echo '${{ toJson(secrets) }}'
                echo '${{ toJson(steps) }}'
                echo '${{ toJson(runner) }}'
              