# api to trigger this workflow: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
name: External Events
on:
  repository_dispatch:

jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Ripository dispatch"