name: Matrix
on: [push]

jobs:
    node-matrix:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [10, 12, 14]
        runs-on: ${{ matrix.os }}
        steps:
          - run: node -v
          - uses: actions/setup-node@v4.0.4
            with:
              node-version: ${{ matrix.node-version }}
          - run: node -v