name: Status Check Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: sleep 90
              timeout-minutes: 1
            - name: Step 2
              id: step-2
              continue-on-error: true
              run: exit 1
            - name: Runs on step-2 failure
              # it needs to have failure() and the previous step to have failed, bacause the default value is success() && ...
              if: failure() && steps.step-2.outcome == 'failure'
              run: echo "This step runs only on step-2 failure"
            - name: Runs on failure
              if: failure()
              run: echo "Failure"
            - name: Runs on Success
              if: success() # This is the default behavior, it is not necessary to specify it
              run: echo "This step runs only on success"
            - name: Always Runs
              if: always()
              run: echo "This step always runs"
            - name: Runs on Cancel
              if: cancelled()
              run: echo "This step runs only on cancel"
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
          - run: echo "Job 2"