name: Calling Reusable
on:
    workflow_dispatch:
      inputs:
         name:
           description: 'Input description'
           type: string
           required: true

jobs:
    # you need to check "Allow all actions and reusable workflows" on Github > Settings > Actions > Geeral > Actions permissions
    calling-a-reusable-wf:
        uses: ./.github/workflows/reusable.yaml
        with:
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}
    calling-a-reusable-wf-2:
        uses: ./.github/workflows/reusable-workflow-with-output.yaml
    using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-wf-2
        steps:
            - run: echo ${{ needs.calling-a-reusable-wf-2.outputs.date }}