name: Calling Reusable
on:
    workflow_dispatch:
      inputs:
         name:
           description: 'Input description'
           type: string
           required: true

jobs:
    # you need to check "Allow all actions and reusable workflows" on Github > Settings > Actions > Geeral > Actions permissions
    calling-a-reusable-wf:
        uses: ./.github/workflows/reusable.yaml
        with:
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}